name: capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=pyh4ca1811_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.17.1=pyhd8ed1ab_0
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py314h5a2d7ad_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h179d6b4_5
  - aws-c-cal=0.9.8=ha82e055_0
  - aws-c-common=0.12.5=hfd05255_1
  - aws-c-compression=0.3.1=h83e01e5_7
  - aws-c-event-stream=0.5.6=hd31a2bc_4
  - aws-c-http=0.10.7=h4b68edd_1
  - aws-c-io=0.23.2=h460b297_2
  - aws-c-mqtt=0.13.3=hfde8714_8
  - aws-c-s3=0.8.6=haf2eb35_7
  - aws-c-sdkutils=0.2.4=h83e01e5_2
  - aws-checksums=0.2.7=h83e01e5_3
  - aws-crt-cpp=0.35.0=hd7c148e_2
  - aws-sdk-cpp=1.11.606=h2b076a5_6
  - babel=2.17.0=pyhd8ed1ab_0
  - bcrypt=5.0.0=py314h9f07db2_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.2.0=py314ha608bb1_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.1=pyhd8ed1ab_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py314h5a2d7ad_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh7428d3b_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h909e829_3
  - cpython=3.14.0=py314hd8ed1ab_102
  - cryptography=46.0.3=py314hb42d478_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - databricks-sdk=0.73.0=pyhd8ed1ab_0
  - debugpy=1.8.17=py314h8b4fd5f_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - dnspython=2.8.0=pyhcf101f3_0
  - docker-py=7.1.0=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fastapi=0.121.1=h4c1cb5d_0
  - fastapi-cli=0.0.16=pyhcf101f3_0
  - fastapi-core=0.121.1=pyhcf101f3_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-cors=6.0.1=pyhe01879c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=pyh7db6752_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=pyhf298e5d_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - graphene=3.4.3=pyhd8ed1ab_1
  - graphite2=1.3.14=hac47afa_2
  - graphql-core=3.2.7=pyhcf101f3_0
  - graphql-relay=3.2.0=pyhd8ed1ab_1
  - greenlet=3.2.4=py314h13fbf68_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h5f2951f_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py314h5a2d7ad_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - invoke=2.2.1=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py314h86ab7b2_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py314hf309875_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=21.0.0=h0832232_11_cpu
  - libarrow-acero=21.0.0=h7d8d6a5_11_cpu
  - libarrow-compute=21.0.0=h2db994a_11_cpu
  - libarrow-dataset=21.0.0=h7d8d6a5_11_cpu
  - libarrow-substrait=21.0.0=hf865cc0_11_cpu
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libclang13=21.1.5=default_ha2db4b5_0
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.86.1=hd9c3897_2
  - libgomp=15.2.0=h1383e82_7
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libparquet=21.0.0=h7051d1f_11_cpu
  - libpng=1.6.50=h7351971_1
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.11.05=h0eb2380_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.0=h0b34c2f_0
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - lz4-c=1.10.0=h2466b09_1
  - mako=1.3.10=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.7=py314h86ab7b2_0
  - matplotlib-base=3.10.7=py314hfa45d96_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_454
  - mlflow=3.5.1=h86ab7b2_1
  - mlflow-skinny=3.5.1=h86ab7b2_1
  - mlflow-ui=3.5.1=py314h86ab7b2_1
  - multidict=6.6.3=pyh62beb40_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.4=py314h06c3c77_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - opentelemetry-api=1.38.0=pyhd8ed1ab_0
  - opentelemetry-proto=1.38.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.38.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.59b0=pyh3cfb1c2_0
  - orc=2.2.1=h7414dfc_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314hd8fd7ce_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py314h93adc56_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=pyhe1237c8_0
  - protobuf=6.31.1=py314h6a447be_2
  - psutil=7.1.3=py314hc5dbbe4_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py314h86ab7b2_1
  - pyarrow-core=21.0.0=py314hb5be3fa_1_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py314h9f07db2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynacl=1.6.0=py314h5a2d7ad_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py314h2c9462b_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.14.0=h4b44e0e_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.14.0=h4df99d1_102
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32=311=py314h8f8f202_1
  - pywin32-on-windows=0.1.0=pyh07e9846_2
  - pywinpty=2.0.15=py314h51f0985_1
  - pyyaml=6.0.3=pyh7db6752_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - rpds-py=0.28.0=py314h9f07db2_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py314h6ca0369_0
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlalchemy=2.0.44=py314h5a2d7ad_0
  - sqlparse=0.5.3=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.49.2=pyhfdc7a7d_0
  - tbb=2022.3.0=hd094cb3_1
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py314h5a2d7ad_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py314h5a2d7ad_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh5737063_0
  - uvicorn-standard=0.38.0=h5737063_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - waitress=3.0.2=pyhd8ed1ab_1
  - watchfiles=1.1.1=py314h170c82c_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py314h4667ab5_2
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py314h5a2d7ad_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=pyh7db6752_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=h32d8bfd_0
  - zstandard=0.25.0=py314hc5dbbe4_1
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - click-config-file==0.6.0
      - click-option-group==0.5.9
      - configobj==5.0.9
      - hydra-core==1.2.0
      - hydra-joblib-launcher==1.2.0
      - iniconfig==2.3.0
      - jinja2schema==0.1.4
      - logbook==1.9.1
      - patsy==1.0.2
      - pexpect==4.9.0
      - pluggy==1.6.0
      - ptyprocess==0.7.0
      - pyclone==2020.9b2
      - pytest==9.0.1
      - ruamel-yaml==0.18.16
      - scipy==1.16.3
      - sentry-sdk==2.44.0
      - statsmodels==0.14.5
      - tempdisagg==0.2.13
      - tqdm==4.67.1
      - wandb==0.23.0
      - wandb-utils==0.1.2
      - wheel==0.45.1
prefix: C:\Users\dalla\miniconda3\envs\capstone
