name: wgu_capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - hydra-core=1.3.2
  - matplotlib=3.10.7
  - pandas=2.3.3
  - jupyterlab=4.4.10
  - pip=25.3
  - pip:
    - mlflow==3.5.1