_wandb:
    value:
        cli_version: 0.23.0
        code_path: source-wgu_capstone-c__Users_dalla_OneDrive_Education_WGU_Capstone_eda_monthly_features_eda.ipynb
        e:
            rjq3kia3axrrcirdoexrzjzt3x57z7gt:
                codePath: c:\Users\dalla\OneDrive\Education\WGU\Capstone\eda\monthly_features_eda.ipynb
                codePathLocal: eda\monthly_features_eda.ipynb
                cpu_count: 12
                cpu_count_logical: 14
                disk:
                    /:
                        total: "252651237376"
                        used: "211323604992"
                email: dallas.taylor96@outlook.com
                executable: C:\Users\dalla\miniconda3\envs\capstone\python.exe
                git:
                    commit: 9841dd964cb9857ebeec6a8523cae494c5f6c85a
                    remote: https://github.com/de-taylor/WGU-Capstone-BSDA.git
                host: DET-WS
                memory:
                    total: "16597598208"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\dalla\OneDrive\Education\WGU\Capstone\eda\monthly_features_eda.ipynb
                python: CPython 3.14.0
                root: C:\Users\dalla\OneDrive\Education\WGU\Capstone
                startedAt: "2025-11-16T01:17:35.393870Z"
                writerId: rjq3kia3axrrcirdoexrzjzt3x57z7gt
        m: []
        python_version: 3.14.0
        t:
            "3":
                - 2
            "4": 3.14.0
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
